var currentPage = 1;

function LangToPT() {
    document.getElementById('title').innerHTML = "Oii! Sou a Yune!"
    document.getElementById('desc').innerHTML = "Esse é o projeto mais simples desenvolvido nesse repositório, mas só fiz esse pq decidi postar um link pra esse repo no LinkedIn e parei pra pensar 'uhh alguém vai ficar bem confuso quando ver meu perfil e pronomes aqui e tudo mais'. Então eu tô fazendo esse mini-proj só pra me introduzir mesmo.<br><br>Sem perder muito tempo, sou trangênero, me identifico como mulher trans. Por isso os pronomes aqui no github são ela/dela, e também por isso o nome 'Yune'. Esse seria o nome que prefiro ser referida. O motivo de não usar esse nome e pronomes no LinkedIn é por que, por enquanto, não me apresento como mulher trans publicamente ainda. No momento só alguns amigos e família sabem. Yeah teóricamente colocar isso tudo aqui pra qualquer um ver é meio bobo e vai fazer isso praticamente público. Mas não é como se eu fosse demorar muito pra fazer isso anyway, e não, eu não vou mudar meus perfis online só pq eu queria colocar algo no LinkedIn, mas eu tô a procura de emprego então meio que precisava deixar algo lá kk<br><br>No momento estou tentando aprender ambos front e back end, para back, escolhi a tecnologia ASP.NET por gostar bastante da linguagem C# e ter um pouco de familiaridade com .net framework. Já Pro front-end, escolhi TailwindCSS. Isso pois Tailwind dá muita liberdade, mais que algo como Bootstrap, e ainda sim é rápido e consíderavelmente fácil de usar, oq faz uma framework incrível pra alguém procurando bastante customização e construir layouts rapidamente"
}

function LangToEN() {
    document.getElementById('title').innerHTML = "Hi there! I'm Yune"
    document.getElementById('desc').innerHTML = "This is the simplest of the projects developed in here, but it's mostly cause I decided to post a link to this repo on LinkedIn and thought 'well shit someone's gonna be confused at my profile and pronouns and all'. So I'm making this for the sake of just, introducing myself.<br><br>So, without beating around the bush too much, I'm transgender, identify as a trans girl. That's why pronouns are she/her in github, also why my name is different in here. I prefer that. The reason I don't use that on LinkedIn however, is cause, as of now, I'm not out publicly. Rn I'm out just to some friends and family. Is putting this info right here for anyone to see dumb and potentially just me coming out publicly? Yeah. Kinda. But it's not like I'm gonna take too long to do so and I am. Not. Changing my online profiles to something I'm less comfortable with just because I wanted to put something on my LinkedIn. Kinda need a job rn y'know lol<br><br>At the moment I'm trying to learn both front and backend. For that, I chose ASP.NET for backend, due to liking C# and being a little bit familiar with the .net framework. As for front-end, I chose TailwindCSS. This is because, Tailwind gives you a lot of freedom, more than something like Bootstrap, and it's quick and fairly easy to do, making it an incredible framework for someone looking for deep customization and doing things quick in the front-end"
}